Defaults: &defaults
  # adapter: sqlite3
  # database: sqlite3.db
  adapter: mysql2
  database: rails3_simple_benchmark_production
  username: root
  password:
  host: localhost

development:
  <<: *defaults
test:
  <<: *defaults
production:
  <<: *defaults
