development:
  adapter: mysql2
  database: rails31_simple_benchmark_production
  username: root
  password:
  host: localhost
  pool: 5
  timeout: 5000
production:
  adapter: mysql2
  database: rails31_simple_benchmark_production
  username: root
  password:
  host: localhost
  pool: 5
  timeout: 5000
