Defaults: &defaults
  # adapter: sqlite3
  # database: sqlite3.db
  adapter: mysql2
  database: rails31_simple_benchmark_production
  username: root
  password:
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *defaults
test:
  <<: *defaults
production:
  <<: *defaults
